package com.pcbxpress.erp.modules.engineering.revisions.dto;

import com.pcbxpress.erp.modules.engineering.revisions.model.ECOChangeRequest;
import com.pcbxpress.erp.modules.engineering.revisions.model.ECOStatus;
import java.time.OffsetDateTime;
import java.util.UUID;

public record ECOChangeRequestDto(
        UUID id,
        String changeRequestNumber,
        UUID jobId,
        String jobNumber,
        String partNumber,
        String revision,
        String title,
        String description,
        String changeType,
        String reason,
        String impactAnalysis,
        String affectedDocuments,
        String affectedParts,
        Double estimatedCost,
        Double estimatedHours,
        String priority,
        UUID requestedBy,
        String requestedByName,
        UUID assignedTo,
        String assignedToName,
        OffsetDateTime dueDate,
        OffsetDateTime targetImplementationDate,
        OffsetDateTime actualImplementationDate,
        ECOStatus status,
        UUID approvedBy,
        String approvedByName,
        OffsetDateTime approvedAt,
        UUID rejectedBy,
        String rejectedByName,
        OffsetDateTime rejectedAt,
        String rejectedReason,
        UUID closedBy,
        String closedByName,
        OffsetDateTime closedAt,
        String closureNotes,
        Integer version,
        boolean isActive,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt) {
    
    public static ECOChangeRequestDto fromEntity(ECOChangeRequest entity) {
        return new ECOChangeRequestDto(
            entity.getId(),
            entity.getChangeRequestNumber(),
            entity.getJobId(),
            entity.getJobNumber(),
            entity.getPartNumber(),
            entity.getRevision(),
            entity.getTitle(),
            entity.getDescription(),
            entity.getChangeType(),
            entity.getReason(),
            entity.getImpactAnalysis(),
            entity.getAffectedDocuments(),
            entity.getAffectedParts(),
            entity.getEstimatedCost(),
            entity.getEstimatedHours(),
            entity.getPriority(),
            entity.getRequestedBy(),
            entity.getRequestedByName(),
            entity.getAssignedTo(),
            entity.getAssignedToName(),
            entity.getDueDate(),
            entity.getTargetImplementationDate(),
            entity.getActualImplementationDate(),
            entity.getStatus(),
            entity.getApprovedBy(),
            entity.getApprovedByName(),
            entity.getApprovedAt(),
            entity.getRejectedBy(),
            entity.getRejectedByName(),
            entity.getRejectedAt(),
            entity.getRejectedReason(),
            entity.getClosedBy(),
            entity.getClosedByName(),
            entity.getClosedAt(),
            entity.getClosureNotes(),
            entity.getVersion(),
            entity.isActive(),
            entity.getCreatedAt(),
            entity.getUpdatedAt()
        );
    }
}