package com.pcbxpress.erp.modules.quality.certificates.repository;

import com.pcbxpress.erp.modules.quality.certificates.model.CoC;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface CoCRepository extends JpaRepository<CoC, Long> {
    
    // Find by CoC number
    Optional<CoC> findByCocNo(String cocNo);
    
    // Find by order number
    List<CoC> findByOrderNo(String orderNo);
    
    // Find by customer
    List<CoC> findByCustomer(String customer);
    
    // Find by customer with pagination
    Page<CoC> findByCustomer(String customer, Pageable pageable);
    
    // Find by lot number
    List<CoC> findByLotNo(String lotNo);
    
    // Find by lot number with pagination
    Page<CoC> findByLotNo(String lotNo, Pageable pageable);
    
    // Find by work order number
    List<CoC> findByWorkOrderNo(String workOrderNo);
    
    // Find by work order number with pagination
    Page<CoC> findByWorkOrderNo(String workOrderNo, Pageable pageable);
    
    // Find by shipment ID
    List<CoC> findByShipmentId(String shipmentId);
    
    // Find by shipment ID with pagination
    Page<CoC> findByShipmentId(String shipmentId, Pageable pageable);
    
    // Find by status
    List<CoC> findByStatus(CoC.Status status);
    
    // Find by status with pagination
    Page<CoC> findByStatus(CoC.Status status, Pageable pageable);
    
    // Find by date range
    List<CoC> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by date range with pagination
    Page<CoC> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by customer and date range
    List<CoC> findByCustomerAndCreatedAtBetween(String customer, LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by customer and date range with pagination
    Page<CoC> findByCustomerAndCreatedAtBetween(String customer, LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by order number and status
    List<CoC> findByOrderNoAndStatus(String orderNo, CoC.Status status);
    
    // Find by order number and status with pagination
    Page<CoC> findByOrderNoAndStatus(String orderNo, CoC.Status status, Pageable pageable);
    
    // Find by customer and status
    List<CoC> findByCustomerAndStatus(String customer, CoC.Status status);
    
    // Find by customer and status with pagination
    Page<CoC> findByCustomerAndStatus(String customer, CoC.Status status, Pageable pageable);
    
    // Find by lot number and status
    List<CoC> findByLotNoAndStatus(String lotNo, CoC.Status status);
    
    // Find by lot number and status with pagination
    Page<CoC> findByLotNoAndStatus(String lotNo, CoC.Status status, Pageable pageable);
    
    // Find by work order number and status
    List<CoC> findByWorkOrderNoAndStatus(String workOrderNo, CoC.Status status);
    
    // Find by work order number and status with pagination
    Page<CoC> findByWorkOrderNoAndStatus(String workOrderNo, CoC.Status status, Pageable pageable);
    
    // Find by shipment ID and status
    List<CoC> findByShipmentIdAndStatus(String shipmentId, CoC.Status status);
    
    // Find by shipment ID and status with pagination
    Page<CoC> findByShipmentIdAndStatus(String shipmentId, CoC.Status status, Pageable pageable);
    
    // Find by generated by user
    List<CoC> findByGeneratedBy(String generatedBy);
    
    // Find by generated by user with pagination
    Page<CoC> findByGeneratedBy(String generatedBy, Pageable pageable);
    
    // Find by sent to user
    List<CoC> findBySentTo(String sentTo);
    
    // Find by sent to user with pagination
    Page<CoC> findBySentTo(String sentTo, Pageable pageable);
    
    // Find by generated by user and status
    List<CoC> findByGeneratedByAndStatus(String generatedBy, CoC.Status status);
    
    // Find by sent to user and status
    List<CoC> findBySentToAndStatus(String sentTo, CoC.Status status);
    
    // Find by carrier
    List<CoC> findByCarrier(String carrier);
    
    // Find by carrier with pagination
    Page<CoC> findByCarrier(String carrier, Pageable pageable);
    
    // Find by carrier and status
    List<CoC> findByCarrierAndStatus(String carrier, CoC.Status status);
    
    // Find by carrier and status with pagination
    Page<CoC> findByCarrierAndStatus(String carrier, CoC.Status status, Pageable pageable);
    
    // Find by AWB
    List<CoC> findByAwb(String awb);
    
    // Find by AWB with pagination
    Page<CoC> findByAwb(String awb, Pageable pageable);
    
    // Find by AWB and status
    List<CoC> findByAwbAndStatus(String awb, CoC.Status status);
    
    // Find by AWB and status with pagination
    Page<CoC> findByAwbAndStatus(String awb, CoC.Status status, Pageable pageable);
    
    // Find by ship date
    List<CoC> findByShipDate(LocalDateTime shipDate);
    
    // Find by ship date with pagination
    Page<CoC> findByShipDate(LocalDateTime shipDate, Pageable pageable);
    
    // Find by ship date range
    List<CoC> findByShipDateBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by ship date range with pagination
    Page<CoC> findByShipDateBetween(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by ship date range and status
    List<CoC> findByShipDateBetweenAndStatus(LocalDateTime startDate, LocalDateTime endDate, CoC.Status status);
    
    // Find by ship date range and status with pagination
    Page<CoC> findByShipDateBetweenAndStatus(LocalDateTime startDate, LocalDateTime endDate, CoC.Status status, Pageable pageable);
    
    // Custom query to find CoCs with optional filters
    @Query("SELECT c FROM CoC c WHERE " +
           "(:customer IS NULL OR c.customer = :customer) AND " +
           "(:status IS NULL OR c.status = :status) AND " +
           "(:startDate IS NULL OR c.createdAt >= :startDate) AND " +
           "(:endDate IS NULL OR c.createdAt <= :endDate) AND " +
           "(:generatedBy IS NULL OR c.generatedBy = :generatedBy)")
    Page<CoC> findWithFilters(@Param("customer") String customer,
                             @Param("status") CoC.Status status,
                             @Param("startDate") LocalDateTime startDate,
                             @Param("endDate") LocalDateTime endDate,
                             @Param("generatedBy") String generatedBy,
                             Pageable pageable);
    
    // Count CoCs by status
    long countByStatus(CoC.Status status);
    
    // Count CoCs by customer
    long countByCustomer(String customer);
    
    // Count CoCs by generated by user
    long countByGeneratedBy(String generatedBy);
    
    // Count CoCs by sent to user
    long countBySentTo(String sentTo);
    
    // Count CoCs by carrier
    long countByCarrier(String carrier);
    
    // Count CoCs by AWB
    long countByAwb(String awb);
    
    // Find the latest CoC number for generating new ones
    @Query("SELECT MAX(c.cocNo) FROM CoC c WHERE c.cocNo LIKE :prefix%")
    String findLatestCocNoByPrefix(@Param("prefix") String prefix);
}