package com.pcbxpress.erp.modules.quality.certificates.repository;

import com.pcbxpress.erp.modules.quality.certificates.model.ComplianceDocs;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface ComplianceDocsRepository extends JpaRepository<ComplianceDocs, Long> {
    
    // Find by document number
    Optional<ComplianceDocs> findByDocumentNo(String documentNo);
    
    // Find by order number
    List<ComplianceDocs> findByOrderNo(String orderNo);
    
    // Find by customer
    List<ComplianceDocs> findByCustomer(String customer);
    
    // Find by customer with pagination
    Page<ComplianceDocs> findByCustomer(String customer, Pageable pageable);
    
    // Find by lot number
    List<ComplianceDocs> findByLotNo(String lotNo);
    
    // Find by lot number with pagination
    Page<ComplianceDocs> findByLotNo(String lotNo, Pageable pageable);
    
    // Find by work order number
    List<ComplianceDocs> findByWorkOrderNo(String workOrderNo);
    
    // Find by work order number with pagination
    Page<ComplianceDocs> findByWorkOrderNo(String workOrderNo, Pageable pageable);
    
    // Find by shipment ID
    List<ComplianceDocs> findByShipmentId(String shipmentId);
    
    // Find by shipment ID with pagination
    Page<ComplianceDocs> findByShipmentId(String shipmentId, Pageable pageable);
    
    // Find by status
    List<ComplianceDocs> findByStatus(ComplianceDocs.Status status);
    
    // Find by status with pagination
    Page<ComplianceDocs> findByStatus(ComplianceDocs.Status status, Pageable pageable);
    
    // Find by date range
    List<ComplianceDocs> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by date range with pagination
    Page<ComplianceDocs> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by customer and date range
    List<ComplianceDocs> findByCustomerAndCreatedAtBetween(String customer, LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by customer and date range with pagination
    Page<ComplianceDocs> findByCustomerAndCreatedAtBetween(String customer, LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by order number and status
    List<ComplianceDocs> findByOrderNoAndStatus(String orderNo, ComplianceDocs.Status status);
    
    // Find by order number and status with pagination
    Page<ComplianceDocs> findByOrderNoAndStatus(String orderNo, ComplianceDocs.Status status, Pageable pageable);
    
    // Find by customer and status
    List<ComplianceDocs> findByCustomerAndStatus(String customer, ComplianceDocs.Status status);
    
    // Find by customer and status with pagination
    Page<ComplianceDocs> findByCustomerAndStatus(String customer, ComplianceDocs.Status status, Pageable pageable);
    
    // Find by lot number and status
    List<ComplianceDocs> findByLotNoAndStatus(String lotNo, ComplianceDocs.Status status);
    
    // Find by lot number and status with pagination
    Page<ComplianceDocs> findByLotNoAndStatus(String lotNo, ComplianceDocs.Status status, Pageable pageable);
    
    // Find by work order number and status
    List<ComplianceDocs> findByWorkOrderNoAndStatus(String workOrderNo, ComplianceDocs.Status status);
    
    // Find by work order number and status with pagination
    Page<ComplianceDocs> findByWorkOrderNoAndStatus(String workOrderNo, ComplianceDocs.Status status, Pageable pageable);
    
    // Find by shipment ID and status
    List<ComplianceDocs> findByShipmentIdAndStatus(String shipmentId, ComplianceDocs.Status status);
    
    // Find by shipment ID and status with pagination
    Page<ComplianceDocs> findByShipmentIdAndStatus(String shipmentId, ComplianceDocs.Status status, Pageable pageable);
    
    // Find by generated by user
    List<ComplianceDocs> findByGeneratedBy(String generatedBy);
    
    // Find by generated by user with pagination
    Page<ComplianceDocs> findByGeneratedBy(String generatedBy, Pageable pageable);
    
    // Find by sent to user
    List<ComplianceDocs> findBySentTo(String sentTo);
    
    // Find by sent to user with pagination
    Page<ComplianceDocs> findBySentTo(String sentTo, Pageable pageable);
    
    // Find by generated by user and status
    List<ComplianceDocs> findByGeneratedByAndStatus(String generatedBy, ComplianceDocs.Status status);
    
    // Find by sent to user and status
    List<ComplianceDocs> findBySentToAndStatus(String sentTo, ComplianceDocs.Status status);
    
    // Find by carrier
    List<ComplianceDocs> findByCarrier(String carrier);
    
    // Find by carrier with pagination
    Page<ComplianceDocs> findByCarrier(String carrier, Pageable pageable);
    
    // Find by carrier and status
    List<ComplianceDocs> findByCarrierAndStatus(String carrier, ComplianceDocs.Status status);
    
    // Find by carrier and status with pagination
    Page<ComplianceDocs> findByCarrierAndStatus(String carrier, ComplianceDocs.Status status, Pageable pageable);
    
    // Find by AWB
    List<ComplianceDocs> findByAwb(String awb);
    
    // Find by AWB with pagination
    Page<ComplianceDocs> findByAwb(String awb, Pageable pageable);
    
    // Find by AWB and status
    List<ComplianceDocs> findByAwbAndStatus(String awb, ComplianceDocs.Status status);
    
    // Find by AWB and status with pagination
    Page<ComplianceDocs> findByAwbAndStatus(String awb, ComplianceDocs.Status status, Pageable pageable);
    
    // Find by ship date
    List<ComplianceDocs> findByShipDate(LocalDateTime shipDate);
    
    // Find by ship date with pagination
    Page<ComplianceDocs> findByShipDate(LocalDateTime shipDate, Pageable pageable);
    
    // Find by ship date range
    List<ComplianceDocs> findByShipDateBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by ship date range with pagination
    Page<ComplianceDocs> findByShipDateBetween(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by ship date range and status
    List<ComplianceDocs> findByShipDateBetweenAndStatus(LocalDateTime startDate, LocalDateTime endDate, ComplianceDocs.Status status);
    
    // Find by ship date range and status with pagination
    Page<ComplianceDocs> findByShipDateBetweenAndStatus(LocalDateTime startDate, LocalDateTime endDate, ComplianceDocs.Status status, Pageable pageable);
    
    // Compliance Docs specific queries
    // Find by document type
    List<ComplianceDocs> findByDocumentType(String documentType);
    
    // Find by document type with pagination
    Page<ComplianceDocs> findByDocumentType(String documentType, Pageable pageable);
    
    // Find by document title
    List<ComplianceDocs> findByDocumentTitle(String documentTitle);
    
    // Find by document title with pagination
    Page<ComplianceDocs> findByDocumentTitle(String documentTitle, Pageable pageable);
    
    // Find by document version
    List<ComplianceDocs> findByDocumentVersion(String documentVersion);
    
    // Find by document version with pagination
    Page<ComplianceDocs> findByDocumentVersion(String documentVersion, Pageable pageable);
    
    // Find by document author
    List<ComplianceDocs> findByDocumentAuthor(String documentAuthor);
    
    // Find by document author with pagination
    Page<ComplianceDocs> findByDocumentAuthor(String documentAuthor, Pageable pageable);
    
    // Find by document approver
    List<ComplianceDocs> findByDocumentApprover(String documentApprover);
    
    // Find by document approver with pagination
    Page<ComplianceDocs> findByDocumentApprover(String documentApprover, Pageable pageable);
    
    // Find by compliance standard
    List<ComplianceDocs> findByComplianceStandard(String complianceStandard);
    
    // Find by compliance standard with pagination
    Page<ComplianceDocs> findByComplianceStandard(String complianceStandard, Pageable pageable);
    
    // Find by compliance level
    List<ComplianceDocs> findByComplianceLevel(String complianceLevel);
    
    // Find by compliance level with pagination
    Page<ComplianceDocs> findByComplianceLevel(String complianceLevel, Pageable pageable);
    
    // Find by compliance scope
    List<ComplianceDocs> findByComplianceScope(String complianceScope);
    
    // Find by compliance scope with pagination
    Page<ComplianceDocs> findByComplianceScope(String complianceScope, Pageable pageable);
    
    // Find by compliance status
    List<ComplianceDocs> findByComplianceStatus(String complianceStatus);
    
    // Find by compliance status with pagination
    Page<ComplianceDocs> findByComplianceStatus(String complianceStatus, Pageable pageable);
    
    // Find by compliance reviewer
    List<ComplianceDocs> findByComplianceReviewer(String complianceReviewer);
    
    // Find by compliance reviewer with pagination
    Page<ComplianceDocs> findByComplianceReviewer(String complianceReviewer, Pageable pageable);
    
    // Find by is public
    List<ComplianceDocs> findByIsPublic(Boolean isPublic);
    
    // Find by is public with pagination
    Page<ComplianceDocs> findByIsPublic(Boolean isPublic, Pageable pageable);
    
    // Find by is archived
    List<ComplianceDocs> findByIsArchived(Boolean isArchived);
    
    // Find by is archived with pagination
    Page<ComplianceDocs> findByIsArchived(Boolean isArchived, Pageable pageable);
    
    // Find by archive reason
    List<ComplianceDocs> findByArchiveReason(String archiveReason);
    
    // Find by archive reason with pagination
    Page<ComplianceDocs> findByArchiveReason(String archiveReason, Pageable pageable);
    
    // Find by archive location
    List<ComplianceDocs> findByArchiveLocation(String archiveLocation);
    
    // Find by archive location with pagination
    Page<ComplianceDocs> findByArchiveLocation(String archiveLocation, Pageable pageable);
    
    // Custom query to find compliance documents with optional filters
    @Query("SELECT c FROM ComplianceDocs c WHERE " +
           "(:customer IS NULL OR c.customer = :customer) AND " +
           "(:status IS NULL OR c.status = :status) AND " +
           "(:startDate IS NULL OR c.createdAt >= :startDate) AND " +
           "(:endDate IS NULL OR c.createdAt <= :endDate) AND " +
           "(:generatedBy IS NULL OR c.generatedBy = :generatedBy) AND " +
           "(:documentType IS NULL OR c.documentType = :documentType) AND " +
           "(:complianceStandard IS NULL OR c.complianceStandard = :complianceStandard) AND " +
           "(:isPublic IS NULL OR c.isPublic = :isPublic) AND " +
           "(:isArchived IS NULL OR c.isArchived = :isArchived)")
    Page<ComplianceDocs> findWithFilters(@Param("customer") String customer,
                                        @Param("status") ComplianceDocs.Status status,
                                        @Param("startDate") LocalDateTime startDate,
                                        @Param("endDate") LocalDateTime endDate,
                                        @Param("generatedBy") String generatedBy,
                                        @Param("documentType") String documentType,
                                        @Param("complianceStandard") String complianceStandard,
                                        @Param("isPublic") Boolean isPublic,
                                        @Param("isArchived") Boolean isArchived,
                                        Pageable pageable);
    
    // Count compliance documents by status
    long countByStatus(ComplianceDocs.Status status);
    
    // Count compliance documents by customer
    long countByCustomer(String customer);
    
    // Count compliance documents by generated by user
    long countByGeneratedBy(String generatedBy);
    
    // Count compliance documents by sent to user
    long countBySentTo(String sentTo);
    
    // Count compliance documents by carrier
    long countByCarrier(String carrier);
    
    // Count compliance documents by AWB
    long countByAwb(String awb);
    
    // Count compliance documents by document type
    long countByDocumentType(String documentType);
    
    // Count compliance documents by compliance standard
    long countByComplianceStandard(String complianceStandard);
    
    // Count compliance documents by compliance level
    long countByComplianceLevel(String complianceLevel);
    
    // Count compliance documents by compliance status
    long countByComplianceStatus(String complianceStatus);
    
    // Count compliance documents by is public
    long countByIsPublic(Boolean isPublic);
    
    // Count compliance documents by is archived
    long countByIsArchived(Boolean isArchived);
    
    // Find the latest document number for generating new ones
    @Query("SELECT MAX(c.documentNo) FROM ComplianceDocs c WHERE c.documentNo LIKE :prefix%")
    String findLatestDocumentNoByPrefix(@Param("prefix") String prefix);
}