package com.pcbxpress.erp.modules.quality.certificates.repository;

import com.pcbxpress.erp.modules.quality.certificates.model.RoHSREACH;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface RoHSREACHRepository extends JpaRepository<RoHSREACH, Long> {
    
    // Find by certificate number
    Optional<RoHSREACH> findByCertificateNo(String certificateNo);
    
    // Find by order number
    List<RoHSREACH> findByOrderNo(String orderNo);
    
    // Find by customer
    List<RoHSREACH> findByCustomer(String customer);
    
    // Find by customer with pagination
    Page<RoHSREACH> findByCustomer(String customer, Pageable pageable);
    
    // Find by lot number
    List<RoHSREACH> findByLotNo(String lotNo);
    
    // Find by lot number with pagination
    Page<RoHSREACH> findByLotNo(String lotNo, Pageable pageable);
    
    // Find by work order number
    List<RoHSREACH> findByWorkOrderNo(String workOrderNo);
    
    // Find by work order number with pagination
    Page<RoHSREACH> findByWorkOrderNo(String workOrderNo, Pageable pageable);
    
    // Find by shipment ID
    List<RoHSREACH> findByShipmentId(String shipmentId);
    
    // Find by shipment ID with pagination
    Page<RoHSREACH> findByShipmentId(String shipmentId, Pageable pageable);
    
    // Find by status
    List<RoHSREACH> findByStatus(RoHSREACH.Status status);
    
    // Find by status with pagination
    Page<RoHSREACH> findByStatus(RoHSREACH.Status status, Pageable pageable);
    
    // Find by date range
    List<RoHSREACH> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by date range with pagination
    Page<RoHSREACH> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by customer and date range
    List<RoHSREACH> findByCustomerAndCreatedAtBetween(String customer, LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by customer and date range with pagination
    Page<RoHSREACH> findByCustomerAndCreatedAtBetween(String customer, LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by order number and status
    List<RoHSREACH> findByOrderNoAndStatus(String orderNo, RoHSREACH.Status status);
    
    // Find by order number and status with pagination
    Page<RoHSREACH> findByOrderNoAndStatus(String orderNo, RoHSREACH.Status status, Pageable pageable);
    
    // Find by customer and status
    List<RoHSREACH> findByCustomerAndStatus(String customer, RoHSREACH.Status status);
    
    // Find by customer and status with pagination
    Page<RoHSREACH> findByCustomerAndStatus(String customer, RoHSREACH.Status status, Pageable pageable);
    
    // Find by lot number and status
    List<RoHSREACH> findByLotNoAndStatus(String lotNo, RoHSREACH.Status status);
    
    // Find by lot number and status with pagination
    Page<RoHSREACH> findByLotNoAndStatus(String lotNo, RoHSREACH.Status status, Pageable pageable);
    
    // Find by work order number and status
    List<RoHSREACH> findByWorkOrderNoAndStatus(String workOrderNo, RoHSREACH.Status status);
    
    // Find by work order number and status with pagination
    Page<RoHSREACH> findByWorkOrderNoAndStatus(String workOrderNo, RoHSREACH.Status status, Pageable pageable);
    
    // Find by shipment ID and status
    List<RoHSREACH> findByShipmentIdAndStatus(String shipmentId, RoHSREACH.Status status);
    
    // Find by shipment ID and status with pagination
    Page<RoHSREACH> findByShipmentIdAndStatus(String shipmentId, RoHSREACH.Status status, Pageable pageable);
    
    // Find by generated by user
    List<RoHSREACH> findByGeneratedBy(String generatedBy);
    
    // Find by generated by user with pagination
    Page<RoHSREACH> findByGeneratedBy(String generatedBy, Pageable pageable);
    
    // Find by sent to user
    List<RoHSREACH> findBySentTo(String sentTo);
    
    // Find by sent to user with pagination
    Page<RoHSREACH> findBySentTo(String sentTo, Pageable pageable);
    
    // Find by generated by user and status
    List<RoHSREACH> findByGeneratedByAndStatus(String generatedBy, RoHSREACH.Status status);
    
    // Find by sent to user and status
    List<RoHSREACH> findBySentToAndStatus(String sentTo, RoHSREACH.Status status);
    
    // Find by carrier
    List<RoHSREACH> findByCarrier(String carrier);
    
    // Find by carrier with pagination
    Page<RoHSREACH> findByCarrier(String carrier, Pageable pageable);
    
    // Find by carrier and status
    List<RoHSREACH> findByCarrierAndStatus(String carrier, RoHSREACH.Status status);
    
    // Find by carrier and status with pagination
    Page<RoHSREACH> findByCarrierAndStatus(String carrier, RoHSREACH.Status status, Pageable pageable);
    
    // Find by AWB
    List<RoHSREACH> findByAwb(String awb);
    
    // Find by AWB with pagination
    Page<RoHSREACH> findByAwb(String awb, Pageable pageable);
    
    // Find by AWB and status
    List<RoHSREACH> findByAwbAndStatus(String awb, RoHSREACH.Status status);
    
    // Find by AWB and status with pagination
    Page<RoHSREACH> findByAwbAndStatus(String awb, RoHSREACH.Status status, Pageable pageable);
    
    // Find by ship date
    List<RoHSREACH> findByShipDate(LocalDateTime shipDate);
    
    // Find by ship date with pagination
    Page<RoHSREACH> findByShipDate(LocalDateTime shipDate, Pageable pageable);
    
    // Find by ship date range
    List<RoHSREACH> findByShipDateBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by ship date range with pagination
    Page<RoHSREACH> findByShipDateBetween(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Find by ship date range and status
    List<RoHSREACH> findByShipDateBetweenAndStatus(LocalDateTime startDate, LocalDateTime endDate, RoHSREACH.Status status);
    
    // Find by ship date range and status with pagination
    Page<RoHSREACH> findByShipDateBetweenAndStatus(LocalDateTime startDate, LocalDateTime endDate, RoHSREACH.Status status, Pageable pageable);
    
    // RoHS/REACH specific queries
    // Find by RoHS compliance
    List<RoHSREACH> findByRohsCompliance(String rohsCompliance);
    
    // Find by RoHS compliance with pagination
    Page<RoHSREACH> findByRohsCompliance(String rohsCompliance, Pageable pageable);
    
    // Find by REACH compliance
    List<RoHSREACH> findByReachCompliance(String reachCompliance);
    
    // Find by REACH compliance with pagination
    Page<RoHSREACH> findByReachCompliance(String reachCompliance, Pageable pageable);
    
    // Find by compliance officer
    List<RoHSREACH> findByComplianceOfficer(String complianceOfficer);
    
    // Find by compliance officer with pagination
    Page<RoHSREACH> findByComplianceOfficer(String complianceOfficer, Pageable pageable);
    
    // Find by test lab
    List<RoHSREACH> findByTestLab(String testLab);
    
    // Find by test lab with pagination
    Page<RoHSREACH> findByTestLab(String testLab, Pageable pageable);
    
    // Find by test report number
    List<RoHSREACH> findByTestReportNo(String testReportNo);
    
    // Find by test report number with pagination
    Page<RoHSREACH> findByTestReportNo(String testReportNo, Pageable pageable);
    
    // Find by certificate authority
    List<RoHSREACH> findByCertificateAuthority(String certificateAuthority);
    
    // Find by certificate authority with pagination
    Page<RoHSREACH> findByCertificateAuthority(String certificateAuthority, Pageable pageable);
    
    // Find by certificate reference
    List<RoHSREACH> findByCertificateReference(String certificateReference);
    
    // Find by certificate reference with pagination
    Page<RoHSREACH> findByCertificateReference(String certificateReference, Pageable pageable);
    
    // Find by certificate expiry date
    List<RoHSREACH> findByCertificateExpiry(LocalDateTime certificateExpiry);
    
    // Find by certificate expiry date with pagination
    Page<RoHSREACH> findByCertificateExpiry(LocalDateTime certificateExpiry, Pageable pageable);
    
    // Find by certificate expiry date range
    List<RoHSREACH> findByCertificateExpiryBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    // Find by certificate expiry date range with pagination
    Page<RoHSREACH> findByCertificateExpiryBetween(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    
    // Custom query to find RoHS/REACH certificates with optional filters
    @Query("SELECT r FROM RoHSREACH r WHERE " +
           "(:customer IS NULL OR r.customer = :customer) AND " +
           "(:status IS NULL OR r.status = :status) AND " +
           "(:startDate IS NULL OR r.createdAt >= :startDate) AND " +
           "(:endDate IS NULL OR r.createdAt <= :endDate) AND " +
           "(:generatedBy IS NULL OR r.generatedBy = :generatedBy) AND " +
           "(:rohsCompliance IS NULL OR r.rohsCompliance = :rohsCompliance) AND " +
           "(:reachCompliance IS NULL OR r.reachCompliance = :reachCompliance)")
    Page<RoHSREACH> findWithFilters(@Param("customer") String customer,
                                   @Param("status") RoHSREACH.Status status,
                                   @Param("startDate") LocalDateTime startDate,
                                   @Param("endDate") LocalDateTime endDate,
                                   @Param("generatedBy") String generatedBy,
                                   @Param("rohsCompliance") String rohsCompliance,
                                   @Param("reachCompliance") String reachCompliance,
                                   Pageable pageable);
    
    // Count RoHS/REACH certificates by status
    long countByStatus(RoHSREACH.Status status);
    
    // Count RoHS/REACH certificates by customer
    long countByCustomer(String customer);
    
    // Count RoHS/REACH certificates by generated by user
    long countByGeneratedBy(String generatedBy);
    
    // Count RoHS/REACH certificates by sent to user
    long countBySentTo(String sentTo);
    
    // Count RoHS/REACH certificates by carrier
    long countByCarrier(String carrier);
    
    // Count RoHS/REACH certificates by AWB
    long countByAwb(String awb);
    
    // Count RoHS/REACH certificates by RoHS compliance
    long countByRohsCompliance(String rohsCompliance);
    
    // Count RoHS/REACH certificates by REACH compliance
    long countByReachCompliance(String reachCompliance);
    
    // Count RoHS/REACH certificates by compliance officer
    long countByComplianceOfficer(String complianceOfficer);
    
    // Count RoHS/REACH certificates by test lab
    long countByTestLab(String testLab);
    
    // Count RoHS/REACH certificates by certificate authority
    long countByCertificateAuthority(String certificateAuthority);
    
    // Find the latest certificate number for generating new ones
    @Query("SELECT MAX(r.certificateNo) FROM RoHSREACH r WHERE r.certificateNo LIKE :prefix%")
    String findLatestCertificateNoByPrefix(@Param("prefix") String prefix);
}