package com.pcbxpress.erp.modules.engineering.panelization.dto;

import com.pcbxpress.erp.modules.engineering.panelization.model.PanelTemplate;
import com.pcbxpress.erp.modules.engineering.panelization.model.PanelStatus;
import java.time.OffsetDateTime;
import java.util.UUID;

public record PanelTemplateDto(
    UUID id,
    String name,
    UUID jobId,
    String jobNumber,
    UUID customerId,
    String customerName,
    String partNumber,
    String revision,
    String description,
    Double panelSizeX,
    Double panelSizeY,
    Double panelThickness,
    String panelMaterial,
    String panelType,
    String routingType,
    boolean vScore,
    boolean tabRout,
    boolean castellatedHoles,
    boolean edgePlating,
    boolean fiducials,
    boolean toolingHoles,
    boolean referenceDesignators,
    boolean componentOutlines,
    String panelizationStyle,
    Integer arrayX,
    Integer arrayY,
    Double boardX,
    Double boardY,
    Double spacingX,
    Double spacingY,
    Double railWidthLeft,
    Double railWidthRight,
    Double railWidthTop,
    Double railWidthBottom,
    boolean railToolingHoles,
    boolean railFiducials,
    String railText,
    boolean breakawayCorners,
    Double cornerRadius,
    boolean mouseBites,
    Double vScoreWidth,
    Double vScoreAngle,
    Double tabWidth,
    Double tabLength,
    Double tabSpacing,
    Double castellatedHoleSize,
    Double castellatedHoleSpacing,
    Double edgePlatingThickness,
    Double fiducialSize,
    Double fiducialClearance,
    Double toolingHoleSize,
    Double toolingHoleClearance,
    Double referenceTextSize,
    Double referenceTextClearance,
    String notes,
    PanelStatus status,
    UUID createdBy,
    String createdByName,
    UUID approvedBy,
    String approvedByName,
    OffsetDateTime approvedAt,
    Integer version,
    boolean isActive,
    boolean isDefault,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt
) {
    public static PanelTemplateDto fromEntity(PanelTemplate template) {
        return new PanelTemplateDto(
            template.getId(),
            template.getName(),
            template.getJobId(),
            template.getJobNumber(),
            template.getCustomerId(),
            template.getCustomerName(),
            template.getPartNumber(),
            template.getRevision(),
            template.getDescription(),
            template.getPanelSizeX(),
            template.getPanelSizeY(),
            template.getPanelThickness(),
            template.getPanelMaterial(),
            template.getPanelType(),
            template.getRoutingType(),
            template.isVScore(),
            template.isTabRout(),
            template.isCastellatedHoles(),
            template.isEdgePlating(),
            template.isFiducials(),
            template.isToolingHoles(),
            template.isReferenceDesignators(),
            template.isComponentOutlines(),
            template.getPanelizationStyle(),
            template.getArrayX(),
            template.getArrayY(),
            template.getBoardX(),
            template.getBoardY(),
            template.getSpacingX(),
            template.getSpacingY(),
            template.getRailWidthLeft(),
            template.getRailWidthRight(),
            template.getRailWidthTop(),
            template.getRailWidthBottom(),
            template.isRailToolingHoles(),
            template.isRailFiducials(),
            template.getRailText(),
            template.isBreakawayCorners(),
            template.getCornerRadius(),
            template.isMouseBites(),
            template.getVScoreWidth(),
            template.getVScoreAngle(),
            template.getTabWidth(),
            template.getTabLength(),
            template.getTabSpacing(),
            template.getCastellatedHoleSize(),
            template.getCastellatedHoleSpacing(),
            template.getEdgePlatingThickness(),
            template.getFiducialSize(),
            template.getFiducialClearance(),
            template.getToolingHoleSize(),
            template.getToolingHoleClearance(),
            template.getReferenceTextSize(),
            template.getReferenceTextClearance(),
            template.getNotes(),
            template.getStatus(),
            template.getCreatedBy(),
            template.getCreatedByName(),
            template.getApprovedBy(),
            template.getApprovedByName(),
            template.getApprovedAt(),
            template.getVersion(),
            template.isActive(),
            template.isDefault(),
            template.getCreatedAt(),
            template.getUpdatedAt()
        );
    }
}