package com.pcbxpress.erp.modules.engineering.dfm.dto;

import com.pcbxpress.erp.modules.engineering.dfm.model.DFMChecklist;
import com.pcbxpress.erp.modules.engineering.dfm.model.DFMStatus;
import java.time.OffsetDateTime;
import java.util.UUID;

public record DFMChecklistDto(
    UUID id,
    UUID jobId,
    String jobNumber,
    UUID customerId,
    String customerName,
    String partNumber,
    String revision,
    Integer layerCount,
    Double boardThickness,
    Double copperThickness,
    String materialType,
    String solderMask,
    String legend,
    String surfaceFinish,
    Double panelSizeX,
    Double panelSizeY,
    Double minTraceWidth,
    Double minTraceSpacing,
    Double minHoleSize,
    Double minAnnularRing,
    Double copperClearance,
    Double soldermaskClearance,
    Double silkscreenClearance,
    boolean viasInPads,
    boolean blindBuriedVias,
    boolean impedanceControlled,
    boolean controlledDepthRouting,
    boolean castellatedHoles,
    boolean edgePlating,
    boolean backdrilling,
    boolean laserDrilling,
    boolean rigidFlex,
    boolean hdi,
    boolean flexRigid,
    boolean flexCable,
    boolean rigidPcb,
    boolean metalCore,
    boolean ceramicSubstrate,
    boolean highFreqMaterial,
    boolean highTempMaterial,
    boolean flexibleMaterial,
    boolean rigidMaterial,
    boolean standardMaterial,
    boolean specialMaterial,
    String materialNotes,
    String designNotes,
    String manufacturingNotes,
    String testNotes,
    String assemblyNotes,
    String packagingNotes,
    String shippingNotes,
    String costNotes,
    String scheduleNotes,
    String qualityNotes,
    String reliabilityNotes,
    String environmentalNotes,
    String complianceNotes,
    String safetyNotes,
    String regulatoryNotes,
    String customerRequirements,
    String engineeringRequirements,
    String manufacturingRequirements,
    String testRequirements,
    String assemblyRequirements,
    String packagingRequirements,
    String shippingRequirements,
    String costRequirements,
    String scheduleRequirements,
    String qualityRequirements,
    String reliabilityRequirements,
    String environmentalRequirements,
    String complianceRequirements,
    String safetyRequirements,
    String regulatoryRequirements,
    DFMStatus status,
    UUID createdBy,
    String createdByName,
    UUID approvedBy,
    String approvedByName,
    OffsetDateTime approvedAt,
    UUID rejectedBy,
    String rejectedByName,
    OffsetDateTime rejectedAt,
    String rejectedReason,
    Integer version,
    boolean isLatest,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt
) {
    public static DFMChecklistDto fromEntity(DFMChecklist checklist) {
        return new DFMChecklistDto(
            checklist.getId(),
            checklist.getJobId(),
            checklist.getJobNumber(),
            checklist.getCustomerId(),
            checklist.getCustomerName(),
            checklist.getPartNumber(),
            checklist.getRevision(),
            checklist.getLayerCount(),
            checklist.getBoardThickness(),
            checklist.getCopperThickness(),
            checklist.getMaterialType(),
            checklist.getSolderMask(),
            checklist.getLegend(),
            checklist.getSurfaceFinish(),
            checklist.getPanelSizeX(),
            checklist.getPanelSizeY(),
            checklist.getMinTraceWidth(),
            checklist.getMinTraceSpacing(),
            checklist.getMinHoleSize(),
            checklist.getMinAnnularRing(),
            checklist.getCopperClearance(),
            checklist.getSoldermaskClearance(),
            checklist.getSilkscreenClearance(),
            checklist.isViasInPads(),
            checklist.isBlindBuriedVias(),
            checklist.isImpedanceControlled(),
            checklist.isControlledDepthRouting(),
            checklist.isCastellatedHoles(),
            checklist.isEdgePlating(),
            checklist.isBackdrilling(),
            checklist.isLaserDrilling(),
            checklist.isRigidFlex(),
            checklist.isHdi(),
            checklist.isFlexRigid(),
            checklist.isFlexCable(),
            checklist.isRigidPcb(),
            checklist.isMetalCore(),
            checklist.isCeramicSubstrate(),
            checklist.isHighFreqMaterial(),
            checklist.isHighTempMaterial(),
            checklist.isFlexibleMaterial(),
            checklist.isRigidMaterial(),
            checklist.isStandardMaterial(),
            checklist.isSpecialMaterial(),
            checklist.getMaterialNotes(),
            checklist.getDesignNotes(),
            checklist.getManufacturingNotes(),
            checklist.getTestNotes(),
            checklist.getAssemblyNotes(),
            checklist.getPackagingNotes(),
            checklist.getShippingNotes(),
            checklist.getCostNotes(),
            checklist.getScheduleNotes(),
            checklist.getQualityNotes(),
            checklist.getReliabilityNotes(),
            checklist.getEnvironmentalNotes(),
            checklist.getComplianceNotes(),
            checklist.getSafetyNotes(),
            checklist.getRegulatoryNotes(),
            checklist.getCustomerRequirements(),
            checklist.getEngineeringRequirements(),
            checklist.getManufacturingRequirements(),
            checklist.getTestRequirements(),
            checklist.getAssemblyRequirements(),
            checklist.getPackagingRequirements(),
            checklist.getShippingRequirements(),
            checklist.getCostRequirements(),
            checklist.getScheduleRequirements(),
            checklist.getQualityRequirements(),
            checklist.getReliabilityRequirements(),
            checklist.getEnvironmentalRequirements(),
            checklist.getComplianceRequirements(),
            checklist.getSafetyRequirements(),
            checklist.getRegulatoryRequirements(),
            checklist.getStatus(),
            checklist.getCreatedBy(),
            checklist.getCreatedByName(),
            checklist.getApprovedBy(),
            checklist.getApprovedByName(),
            checklist.getApprovedAt(),
            checklist.getRejectedBy(),
            checklist.getRejectedByName(),
            checklist.getRejectedAt(),
            checklist.getRejectedReason(),
            checklist.getVersion(),
            checklist.isLatest(),
            checklist.getCreatedAt(),
            checklist.getUpdatedAt()
        );
    }
}