package com.pcbxpress.erp.modules.engineering.cam.dto;

import com.pcbxpress.erp.modules.engineering.cam.model.CamJob;
import com.pcbxpress.erp.modules.engineering.cam.model.CamJobStatus;
import java.time.OffsetDateTime;
import java.util.UUID;

public record CamJobDto(
    UUID id,
    String jobNumber,
    UUID customerId,
    String customerName,
    String partNumber,
    String revision,
    String description,
    Integer layerCount,
    Double boardThickness,
    Double copperThickness,
    String materialType,
    String solderMask,
    String legend,
    String surfaceFinish,
    Double panelSizeX,
    Double panelSizeY,
    String panelizationType,
    String routingType,
    boolean vScore,
    boolean tabRout,
    boolean castellatedHoles,
    boolean edgePlating,
    boolean impedanceControl,
    boolean testPoints,
    boolean fiducials,
    boolean toolingHoles,
    boolean referenceDesignators,
    boolean componentOutlines,
    String assemblyVariants,
    String specialInstructions,
    CamJobStatus status,
    String gerberFiles,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt,
    OffsetDateTime completedAt,
    UUID assignedTo,
    String assignedName,
    String priority,
    Double estimatedHours,
    Double actualHours,
    String notes
) {
    public static CamJobDto fromEntity(CamJob camJob) {
        return new CamJobDto(
            camJob.getId(),
            camJob.getJobNumber(),
            camJob.getCustomerId(),
            camJob.getCustomerName(),
            camJob.getPartNumber(),
            camJob.getRevision(),
            camJob.getDescription(),
            camJob.getLayerCount(),
            camJob.getBoardThickness(),
            camJob.getCopperThickness(),
            camJob.getMaterialType(),
            camJob.getSolderMask(),
            camJob.getLegend(),
            camJob.getSurfaceFinish(),
            camJob.getPanelSizeX(),
            camJob.getPanelSizeY(),
            camJob.getPanelizationType(),
            camJob.getRoutingType(),
            camJob.isVScore(),
            camJob.isTabRout(),
            camJob.isCastellatedHoles(),
            camJob.isEdgePlating(),
            camJob.isImpedanceControl(),
            camJob.isTestPoints(),
            camJob.isFiducials(),
            camJob.isToolingHoles(),
            camJob.isReferenceDesignators(),
            camJob.isComponentOutlines(),
            camJob.getAssemblyVariants(),
            camJob.getSpecialInstructions(),
            camJob.getStatus(),
            camJob.getGerberFiles(),
            camJob.getCreatedAt(),
            camJob.getUpdatedAt(),
            camJob.getCompletedAt(),
            camJob.getAssignedTo(),
            camJob.getAssignedName(),
            camJob.getPriority(),
            camJob.getEstimatedHours(),
            camJob.getActualHours(),
            camJob.getNotes()
        );
    }
}