package com.pcbxpress.erp.modules.engineering.stackup.dto;

import com.pcbxpress.erp.modules.engineering.stackup.model.MaterialRule;
import java.time.OffsetDateTime;
import java.util.UUID;

public record MaterialRuleDto(
    UUID id,
    String materialType,
    String ruleType,
    String ruleName,
    String ruleDescription,
    Double minValue,
    Double maxValue,
    Double targetValue,
    Double tolerance,
    String unit,
    Integer layerCountMin,
    Integer layerCountMax,
    Double thicknessMin,
    Double thicknessMax,
    Double copperThicknessMin,
    Double copperThicknessMax,
    Double dielectricConstantMin,
    Double dielectricConstantMax,
    Double dissipationFactorMin,
    Double dissipationFactorMax,
    String glassWeaveType,
    String glassWeaveStyle,
    String prepregType,
    String coreType,
    String surfaceFinish,
    boolean impedanceControlled,
    boolean platedHoles,
    boolean nonPlatedHoles,
    boolean castellatedHoles,
    boolean edgePlating,
    boolean rigidFlex,
    boolean flexRigid,
    boolean flexCable,
    boolean metalCore,
    boolean ceramicSubstrate,
    boolean highFreqMaterial,
    boolean highTempMaterial,
    boolean flexibleMaterial,
    boolean rigidMaterial,
    boolean standardMaterial,
    boolean specialMaterial,
    boolean isActive,
    boolean isDefault,
    String notes,
    UUID createdBy,
    String createdByName,
    UUID approvedBy,
    String approvedByName,
    OffsetDateTime approvedAt,
    Integer version,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt
) {
    public static MaterialRuleDto fromEntity(MaterialRule rule) {
        return new MaterialRuleDto(
            rule.getId(),
            rule.getMaterialType(),
            rule.getRuleType(),
            rule.getRuleName(),
            rule.getRuleDescription(),
            rule.getMinValue(),
            rule.getMaxValue(),
            rule.getTargetValue(),
            rule.getTolerance(),
            rule.getUnit(),
            rule.getLayerCountMin(),
            rule.getLayerCountMax(),
            rule.getThicknessMin(),
            rule.getThicknessMax(),
            rule.getCopperThicknessMin(),
            rule.getCopperThicknessMax(),
            rule.getDielectricConstantMin(),
            rule.getDielectricConstantMax(),
            rule.getDissipationFactorMin(),
            rule.getDissipationFactorMax(),
            rule.getGlassWeaveType(),
            rule.getGlassWeaveStyle(),
            rule.getPrepregType(),
            rule.getCoreType(),
            rule.getSurfaceFinish(),
            rule.isImpedanceControlled(),
            rule.isPlatedHoles(),
            rule.isNonPlatedHoles(),
            rule.isCastellatedHoles(),
            rule.isEdgePlating(),
            rule.isRigidFlex(),
            rule.isFlexRigid(),
            rule.isFlexCable(),
            rule.isMetalCore(),
            rule.isCeramicSubstrate(),
            rule.isHighFreqMaterial(),
            rule.isHighTempMaterial(),
            rule.isFlexibleMaterial(),
            rule.isRigidMaterial(),
            rule.isStandardMaterial(),
            rule.isSpecialMaterial(),
            rule.isActive(),
            rule.isDefault(),
            rule.getNotes(),
            rule.getCreatedBy(),
            rule.getCreatedByName(),
            rule.getApprovedBy(),
            rule.getApprovedByName(),
            rule.getApprovedAt(),
            rule.getVersion(),
            rule.getCreatedAt(),
            rule.getUpdatedAt()
        );
    }
}