package com.pcbxpress.erp.modules.engineering.stackup.dto;

import com.pcbxpress.erp.modules.engineering.stackup.model.StackupTemplate;
import java.time.OffsetDateTime;
import java.util.UUID;

public record StackupTemplateDto(
    UUID id,
    String name,
    String description,
    Integer layerCount,
    Double totalThickness,
    Double copperThickness,
    String materialType,
    Double dielectricConstant,
    Double dissipationFactor,
    String glassWeaveType,
    String glassWeaveStyle,
    String prepregType,
    Double prepregThickness,
    String coreType,
    Double coreThickness,
    Double solderMaskThickness,
    Double legendThickness,
    String surfaceFinish,
    boolean impedanceControlled,
    String controlledImpedanceLayers,
    Double targetImpedance,
    Double impedanceTolerance,
    Double traceWidth,
    Double traceSpacing,
    Double viaSize,
    Double viaPadSize,
    Double viaClearance,
    Double microviaSize,
    Double microviaPadSize,
    Double blindViaSize,
    Double buriedViaSize,
    Double laserViaSize,
    Double backdrillSize,
    boolean platedHoles,
    boolean nonPlatedHoles,
    boolean castellatedHoles,
    boolean edgePlating,
    boolean rigidFlex,
    boolean flexRigid,
    boolean flexCable,
    boolean metalCore,
    boolean ceramicSubstrate,
    boolean highFreqMaterial,
    boolean highTempMaterial,
    boolean flexibleMaterial,
    boolean rigidMaterial,
    boolean standardMaterial,
    boolean specialMaterial,
    String notes,
    UUID createdBy,
    String createdByName,
    UUID approvedBy,
    String approvedByName,
    OffsetDateTime approvedAt,
    Integer version,
    boolean isActive,
    boolean isDefault,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt
) {
    public static StackupTemplateDto fromEntity(StackupTemplate template) {
        return new StackupTemplateDto(
            template.getId(),
            template.getName(),
            template.getDescription(),
            template.getLayerCount(),
            template.getTotalThickness(),
            template.getCopperThickness(),
            template.getMaterialType(),
            template.getDielectricConstant(),
            template.getDissipationFactor(),
            template.getGlassWeaveType(),
            template.getGlassWeaveStyle(),
            template.getPrepregType(),
            template.getPrepregThickness(),
            template.getCoreType(),
            template.getCoreThickness(),
            template.getSolderMaskThickness(),
            template.getLegendThickness(),
            template.getSurfaceFinish(),
            template.isImpedanceControlled(),
            template.getControlledImpedanceLayers(),
            template.getTargetImpedance(),
            template.getImpedanceTolerance(),
            template.getTraceWidth(),
            template.getTraceSpacing(),
            template.getViaSize(),
            template.getViaPadSize(),
            template.getViaClearance(),
            template.getMicroviaSize(),
            template.getMicroviaPadSize(),
            template.getBlindViaSize(),
            template.getBuriedViaSize(),
            template.getLaserViaSize(),
            template.getBackdrillSize(),
            template.isPlatedHoles(),
            template.isNonPlatedHoles(),
            template.isCastellatedHoles(),
            template.isEdgePlating(),
            template.isRigidFlex(),
            template.isFlexRigid(),
            template.isFlexCable(),
            template.isMetalCore(),
            template.isCeramicSubstrate(),
            template.isHighFreqMaterial(),
            template.isHighTempMaterial(),
            template.isFlexibleMaterial(),
            template.isRigidMaterial(),
            template.isStandardMaterial(),
            template.isSpecialMaterial(),
            template.getNotes(),
            template.getCreatedBy(),
            template.getCreatedByName(),
            template.getApprovedBy(),
            template.getApprovedByName(),
            template.getApprovedAt(),
            template.getVersion(),
            template.isActive(),
            template.isDefault(),
            template.getCreatedAt(),
            template.getUpdatedAt()
        );
    }
}